# Generated by Django 3.2.5 on 2021-07-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
                ('user_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
