# Generated by Django 3.2.5 on 2021-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ST_User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
                ('user_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'st_user',
                'managed': False,
            },
        ),
    ]
