# Generated by Django 3.2.5 on 2021-08-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0003_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_page', models.IntegerField()),
                ('keyword_contents', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_page', models.IntegerField()),
                ('script_contents', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'script',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
