# Generated by Django 3.2.5 on 2021-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0004_auto_20210814_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='presentation_file')),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
    ]
