# Generated by Django 3.2.5 on 2021-08-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0005_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationFile',
            fields=[
                ('presentationfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='presentation_file')),
            ],
            options={
                'db_table': 'presentation_file',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
