# Generated by Django 3.2.5 on 2021-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0006_auto_20210823_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationResult',
            fields=[
                ('presentation_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('presentation_result_time', models.TimeField()),
                ('presentation_result_score', models.IntegerField(blank=True, null=True)),
                ('presentation_result_dupword', models.TextField(blank=True, null=True)),
                ('presentation_result_improper', models.TextField(blank=True, null=True)),
                ('presentation_result_fillerwords', models.TextField(blank=True, null=True)),
                ('presentation_result_stammering', models.TextField(blank=True, null=True)),
                ('presentation_result_gap', models.TextField(blank=True, null=True)),
                ('presentation_result_shake', models.TextField(blank=True, null=True)),
                ('presentation_result_tune', models.TextField(blank=True, null=True)),
                ('presentation_result_speed', models.TextField(blank=True, null=True)),
                ('presentation_result_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'presentation_result',
                'managed': False,
            },
        ),
    ]
