# Generated by Django 3.2.5 on 2021-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0007_presentationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowhow',
            fields=[
                ('knowhow_id', models.AutoField(primary_key=True, serialize=False)),
                ('knowhow_title', models.CharField(max_length=255)),
                ('knowhow_img', models.FileField(blank=True, null=True, upload_to='knowhow_img')),
                ('knowhow_contents', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knowhow',
                'managed': False,
            },
        ),
    ]
