# Generated by Django 3.2.5 on 2021-11-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_teacher', '0008_knowhow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTDB',
            fields=[
                ('testdb_id', models.AutoField(primary_key=True, serialize=False)),
                ('testdb_num', models.IntegerField()),
                ('testdb_string', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'testdb',
                'managed': False,
            },
        ),
    ]
